# Generated by Django 4.2.6 on 2023-11-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'ordering': ['id'], 'verbose_name': 'Linea Pedido', 'verbose_name_plural': 'Linea Pedidos'},
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterModelTable(
            name='lineapedido',
            table='lineapedidos',
        ),
    ]
