# Generated by Django 4.2.6 on 2023-11-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0002_alter_lineapedido_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lineapedido',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pedido',
            table=None,
        ),
    ]
