# Generated by Django 4.2.6 on 2023-11-02 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosApp', '0004_lineapedido_creado_lineapedido_update_pedido_creado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
